#!/usr/bin/env bash
# =============================================================================
# evtx_pipeline.sh — Flatten + Normalize Windows NDJSON logs
#
# Usage:
#   ./evtx_pipeline.sh <input_file> <output_file> [options]
#
# Output schema:
#   - Field order: TimeGenerated, EventID, EventDescription, Computer → rest → AdditionalFields → EventData
#   - All System fields are flattened to top level
#   - Low-value metadata fields packed into AdditionalFields (null if all absent)
#   - EventData is kept as a nested JSON object (always last)
#   - %% codes in EventData resolved via msobjs_lookup.json (Option B: keep code + append description)
#   - EventDescription resolved via two-tier lookup:
#       1. master_security_auditing_index_micosoft.json (must be in same dir as script)
#       2. --lookup file (optional fallback for EventIDs not in master)
#       3. msobjs_lookup.json (must be in same dir as script)
#
# Options:
#   --lookup  <file>   Optional fallback lookup (generated by generate_lookup.ps1)
#   --warnings <file>  Warnings log path. Default: warnings.log
#
# Examples:
#   ./evtx_pipeline.sh Security.json out.ndjson
#   ./evtx_pipeline.sh Security.json out.ndjson --lookup soc_event_lookup.json
#   ./evtx_pipeline.sh Security.json out.ndjson --lookup soc_event_lookup.json --warnings w.log
#
# Requirements: jq >= 1.6, bash >= 4
# =============================================================================

set -euo pipefail

# ── Script directory (master + msobjs files must live here) ───────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MASTER="${SCRIPT_DIR}/master_security_auditing_index_micosoft.json"
MSOBJS="${SCRIPT_DIR}/msobjs_lookup.json"

# ── Defaults ──────────────────────────────────────────────────────────────────
INPUT=""
OUTPUT=""
WARNINGS="warnings.log"
LOOKUP=""

# ── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --lookup)
            LOOKUP="${2:-}"
            [[ -z "$LOOKUP" ]] && { echo "ERROR: --lookup requires a filename."; exit 1; }
            shift 2
            ;;
        --warnings)
            WARNINGS="${2:-}"
            [[ -z "$WARNINGS" ]] && { echo "ERROR: --warnings requires a filename."; exit 1; }
            shift 2
            ;;
        -*)
            echo "ERROR: Unknown option '$1'"
            echo "Usage: $0 <input_file> <output_file> [--lookup <file>] [--warnings <file>]"
            exit 1
            ;;
        *)
            if [[ -z "$INPUT" ]]; then
                INPUT="$1"
            elif [[ -z "$OUTPUT" ]]; then
                OUTPUT="$1"
            else
                echo "ERROR: Unexpected argument '$1'"
                exit 1
            fi
            shift
            ;;
    esac
done

if [[ -z "$INPUT" || -z "$OUTPUT" ]]; then
    echo "Usage: $0 <input_file> <output_file> [--lookup <file>] [--warnings <file>]"
    exit 1
fi

if [[ ! -f "$MASTER" ]]; then
    echo "ERROR: Master lookup file not found: $MASTER"
    echo "       Place master_security_auditing_index_micosoft.json in the same directory as this script."
    exit 1
fi

if [[ ! -f "$MSOBJS" ]]; then
    echo "ERROR: msobjs lookup file not found: $MSOBJS"
    echo "       Place msobjs_lookup.json in the same directory as this script."
    echo "       Generate it using: generate_msobjs_lookup.ps1 (run on a Windows DC or Server)"
    exit 1
fi

if [[ ! -f "$INPUT" ]]; then
    echo "ERROR: Input file '$INPUT' does not exist."
    exit 1
fi

if [[ -n "$LOOKUP" && ! -f "$LOOKUP" ]]; then
    echo "ERROR: Lookup file '$LOOKUP' does not exist."
    exit 1
fi

# ── Temp files ────────────────────────────────────────────────────────────────
TMP_FLAT=$(mktemp /tmp/pipeline_flat_XXXXXX.ndjson)
TMP_WARN=$(mktemp /tmp/pipeline_warn_XXXXXX.txt)

cleanup() {
    rm -f "$TMP_FLAT" "$TMP_WARN" "${TMP_FLAT}.clean" 2>/dev/null
}
trap cleanup EXIT

# ── Pre-count ─────────────────────────────────────────────────────────────────
TOTAL_LINES=$(wc -l < "$INPUT")
> "$WARNINGS"

# ── Header ────────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║         EVTX JSON Flatten + Normalize Pipeline       ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  Input     : $INPUT"
echo "  Output    : $OUTPUT"
echo "  Master    : $MASTER"
echo "  msobjs    : $MSOBJS"
if [[ -n "$LOOKUP" ]]; then
    echo "  Fallback  : $LOOKUP"
else
    echo "  Fallback  : (none)"
fi
echo "  Warnings  : $WARNINGS"
echo "  Lines     : $TOTAL_LINES"
echo ""

# =============================================================================
# STAGE 1: FLATTEN
#
# - Flattens all sections EXCEPT EventData
# - EventData is preserved as-is (nested object)
# - Tags bad records as { "__warn": N }
# =============================================================================

echo "[ STAGE 1 ] Flattening..."
echo ""

jq -cn '
def flatten_obj(prefix; obj):
  reduce (obj | to_entries[]) as $item (
    {};
    ($item.key
      | gsub("#attributes"; "")
      | ltrimstr("_")
      | rtrimstr("_")
    ) as $clean |
    (if prefix == "" then $clean
     else prefix + "_" + $clean
     end) as $full |
    if $clean == "" then
      if ($item.value | type) == "object" then
        . + flatten_obj(prefix; $item.value)
      else . end
    elif ($item.value | type) == "object" then
      . + flatten_obj($full; $item.value)
    elif ($item.value | type) == "array" then
      . + (
        reduce range($item.value | length) as $i (
          {};
          ($full + "_" + ($i | tostring)) as $ak |
          if ($item.value[$i] | type) == "object" then
            . + flatten_obj($ak; $item.value[$i])
          else
            . + { ($ak): $item.value[$i] }
          end
        )
      )
    else
      . + { ($full): $item.value }
    end
  );

def process_event(evt):
  # Separate EventData from all other sections
  (evt | to_entries | map(select(.key != "EventData" and .key != "UserData"))) as $other_sections |
  (evt.EventData // evt.UserData // null) as $event_data |

  # Flatten all non-EventData sections
  (reduce $other_sections[] as $section (
    {};
    if ($section.value | type) == "object" then
      . + flatten_obj(""; $section.value)
    elif ($section.value | type) == "array" then
      . + (
        reduce range($section.value | length) as $i (
          {};
          ($section.key + "_" + ($i | tostring)) as $ak |
          if ($section.value[$i] | type) == "object" then
            . + flatten_obj($ak; $section.value[$i])
          else
            . + { ($ak): $section.value[$i] }
          end
        )
      )
    elif $section.value == null then .
    else . + { ($section.key): $section.value }
    end
  )) as $flat |

  # Return flat fields + EventData as nested object
  $flat + { "EventData": $event_data };

[inputs] |
to_entries[] |
.key as $lineno |
.value as $rec |
if $rec | has("Event") then
  process_event($rec.Event)
else
  { "__warn": ($lineno + 1) }
end
' "$INPUT" > "$TMP_FLAT"

# ── Split warnings ────────────────────────────────────────────────────────────
jq -c 'select(has("__warn") | not)' "$TMP_FLAT" > "${TMP_FLAT}.clean"
jq -r 'select(has("__warn")) | "[WARN] Line \(.__warn) is missing .Event field — skipped."' \
    "$TMP_FLAT" > "$TMP_WARN"

mv "${TMP_FLAT}.clean" "$TMP_FLAT"
cp "$TMP_WARN" "$WARNINGS"

FLAT_RECORDS=$(wc -l < "$TMP_FLAT")
SKIPPED_RECORDS=$(wc -l < "$TMP_WARN")

echo "  Flattened : $FLAT_RECORDS records"
echo "  Skipped   : $SKIPPED_RECORDS records"
echo ""

if [[ $FLAT_RECORDS -eq 0 ]]; then
    echo "ERROR: No records flattened. Check warnings file."
    exit 1
fi

# =============================================================================
# STAGE 2: ENRICH + NORMALIZE
#
# - Builds master map (first priority) + fallback map (second priority, optional)
# - Looks up EventDescription via Provider_Name + EventID
# - Builds msobjs map for %% code replacement inside EventData
# - Field order: TimeGenerated, EventID, EventDescription, Computer → rest → AdditionalFields → EventData
# - Packs low-value metadata into AdditionalFields (null if all fields absent)
#   Packed fields: Provider_Guid, Version, Level, Task, Opcode, Keywords,
#                  EventRecordID, Execution_ProcessID, Execution_ThreadID
# - Renames TimeCreated_SystemTime → TimeGenerated
# - Drops xmlns column
# - No match in either lookup → EventDescription: null
# - %% codes not in msobjs → left as-is
# =============================================================================

echo "[ STAGE 2 ] Enriching and normalizing..."
echo ""

# Fields to pack into AdditionalFields
ADDITIONAL_FIELDS='["Provider_Guid","Version","Level","Task","Opcode","Keywords","EventRecordID","Execution_ProcessID","Execution_ThreadID"]'

if [[ -n "$LOOKUP" ]]; then
    jq -cn \
      --slurpfile master "$MASTER" \
      --slurpfile fallback "$LOOKUP" \
      --slurpfile msobjs "$MSOBJS" \
      --argjson additional_fields "$ADDITIONAL_FIELDS" '
    # Build master map: "Provider_EventID" -> Description
    (
      $master[0] |
      map({ ((.Provider + "_" + (.EventID | tostring))): .Description }) |
      add // {}
    ) as $master_map |

    # Build fallback map
    (
      $fallback[0] |
      map({ ((.Provider + "_" + (.EventID | tostring))): .Description }) |
      add // {}
    ) as $fallback_map |

    # Merge: master takes precedence, fallback fills gaps
    ($fallback_map + $master_map) as $lookup_map |

    # Build msobjs map: "%%XXXX" -> "%%XXXX (Description)"
    (
      $msobjs[0] |
      map({ (.Code): (.Code + " (" + .Description + ")") }) |
      add // {}
    ) as $msobjs_map |

    # Build additional fields set for quick lookup
    ($additional_fields | map({(.): true}) | add) as $additional_set |

    [inputs] | .[] | . as $rec |

    # Lookup EventDescription
    (($rec.Provider_Name // "") + "_" + ($rec.EventID // "" | tostring)) as $key |
    ($lookup_map[$key] // null) as $description |

    # Normalize TimeGenerated
    ($rec | if has("TimeCreated_SystemTime") then
      .TimeGenerated = .TimeCreated_SystemTime | del(.TimeCreated_SystemTime)
    else . end) as $rec |

    # Replace %% codes in EventData string values
    (if $rec.EventData != null then
      $rec.EventData | walk(
        if type == "string" then
          . as $str |
          reduce ($msobjs_map | keys[]) as $code (
            $str;
            gsub($code; $msobjs_map[$code])
          )
        else . end
      )
    else null end) as $enriched_event_data |

    # Build AdditionalFields — pack low-value metadata fields
    (reduce $additional_fields[] as $f (
      {};
      if $rec[$f] != null then .[$f] = $rec[$f] else . end
    )) as $af_obj |
    (if ($af_obj | length) > 0 then $af_obj else null end) as $additional_fields_val |

    # Build output with correct field order
    { TimeGenerated: ($rec.TimeGenerated // null) }
    + { EventID: $rec.EventID }
    + { EventDescription: $description }
    + { Computer: ($rec.Computer // null) }
    + (
        $rec
        | del(.TimeGenerated)
        | del(.EventID)
        | del(.Computer)
        | del(.EventData)
        | del(.xmlns)
        | del(.TimeCreated_SystemTime)
        | with_entries(select(.key as $k | $additional_set[$k] | not))
      )
    + { AdditionalFields: $additional_fields_val }
    + { EventData: $enriched_event_data }
    ' "$TMP_FLAT" > "$OUTPUT"
else
    jq -cn \
      --slurpfile master "$MASTER" \
      --slurpfile msobjs "$MSOBJS" \
      --argjson additional_fields "$ADDITIONAL_FIELDS" '
    # Build master map only
    (
      $master[0] |
      map({ ((.Provider + "_" + (.EventID | tostring))): .Description }) |
      add // {}
    ) as $lookup_map |

    # Build msobjs map: "%%XXXX" -> "%%XXXX (Description)"
    (
      $msobjs[0] |
      map({ (.Code): (.Code + " (" + .Description + ")") }) |
      add // {}
    ) as $msobjs_map |

    # Build additional fields set for quick lookup
    ($additional_fields | map({(.): true}) | add) as $additional_set |

    [inputs] | .[] | . as $rec |

    # Lookup EventDescription
    (($rec.Provider_Name // "") + "_" + ($rec.EventID // "" | tostring)) as $key |
    ($lookup_map[$key] // null) as $description |

    # Normalize TimeGenerated
    ($rec | if has("TimeCreated_SystemTime") then
      .TimeGenerated = .TimeCreated_SystemTime | del(.TimeCreated_SystemTime)
    else . end) as $rec |

    # Replace %% codes in EventData string values
    (if $rec.EventData != null then
      $rec.EventData | walk(
        if type == "string" then
          . as $str |
          reduce ($msobjs_map | keys[]) as $code (
            $str;
            gsub($code; $msobjs_map[$code])
          )
        else . end
      )
    else null end) as $enriched_event_data |

    # Build AdditionalFields — pack low-value metadata fields
    (reduce $additional_fields[] as $f (
      {};
      if $rec[$f] != null then .[$f] = $rec[$f] else . end
    )) as $af_obj |
    (if ($af_obj | length) > 0 then $af_obj else null end) as $additional_fields_val |

    # Build output with correct field order
    { TimeGenerated: ($rec.TimeGenerated // null) }
    + { EventID: $rec.EventID }
    + { EventDescription: $description }
    + { Computer: ($rec.Computer // null) }
    + (
        $rec
        | del(.TimeGenerated)
        | del(.EventID)
        | del(.Computer)
        | del(.EventData)
        | del(.xmlns)
        | del(.TimeCreated_SystemTime)
        | with_entries(select(.key as $k | $additional_set[$k] | not))
      )
    + { AdditionalFields: $additional_fields_val }
    + { EventData: $enriched_event_data }
    ' "$TMP_FLAT" > "$OUTPUT"
fi

OUTPUT_RECORDS=$(wc -l < "$OUTPUT")

echo "  Enriched  : $OUTPUT_RECORDS records"
echo ""

# =============================================================================
# SUMMARY
# =============================================================================

echo "╔══════════════════════════════════════════════════════╗"
echo "║                      SUMMARY                        ║"
echo "╚══════════════════════════════════════════════════════╝"
printf "  %-30s %s\n" "Total lines in file:"    "$TOTAL_LINES"
printf "  %-30s %s\n" "Successfully flattened:" "$FLAT_RECORDS"
printf "  %-30s %s\n" "Skipped (no .Event):"    "$SKIPPED_RECORDS"
printf "  %-30s %s\n" "Output records:"         "$OUTPUT_RECORDS"
printf "  %-30s %s\n" "Output:"                 "$OUTPUT"
printf "  %-30s %s\n" "Master lookup:"          "$MASTER"
printf "  %-30s %s\n" "msobjs lookup:"          "$MSOBJS"
if [[ -n "$LOOKUP" ]]; then
    printf "  %-30s %s\n" "Fallback lookup:"    "$LOOKUP"
fi
if [[ $SKIPPED_RECORDS -gt 0 ]]; then
    printf "  %-30s %s\n" "Warnings:"           "$WARNINGS"
fi
echo ""
echo "  Done."
echo ""
