#!/usr/bin/env bash
# =============================================================================
# evtx_pipeline.sh — Flatten + Normalize Windows NDJSON logs
#
# Usage:
#   ./evtx_pipeline.sh <input_file> <output_file> [options]
#
# Output schema:
#   - All System fields are flattened to top level
#   - EventData is kept as a nested JSON object
#   - EventDescription resolved via two-tier lookup:
#       1. master_security_auditing_index_micosoft.json (must be in same dir as script)
#       2. --lookup file (optional fallback for EventIDs not in master)
#
# Options:
#   --lookup  <file>   Optional fallback lookup (generated by generate_lookup.ps1)
#   --warnings <file>  Warnings log path. Default: warnings.log
#
# Examples:
#   ./evtx_pipeline.sh Security.json out.ndjson
#   ./evtx_pipeline.sh Security.json out.ndjson --lookup soc_event_lookup.json
#   ./evtx_pipeline.sh Security.json out.ndjson --lookup soc_event_lookup.json --warnings w.log
#
# Requirements: jq >= 1.6, bash >= 4
# =============================================================================

set -euo pipefail

# ── Script directory (master file must live here) ─────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MASTER="${SCRIPT_DIR}/master_security_auditing_index_micosoft.json"

# ── Defaults ──────────────────────────────────────────────────────────────────
INPUT=""
OUTPUT=""
WARNINGS="warnings.log"
LOOKUP=""

# ── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --lookup)
            LOOKUP="${2:-}"
            [[ -z "$LOOKUP" ]] && { echo "ERROR: --lookup requires a filename."; exit 1; }
            shift 2
            ;;
        --warnings)
            WARNINGS="${2:-}"
            [[ -z "$WARNINGS" ]] && { echo "ERROR: --warnings requires a filename."; exit 1; }
            shift 2
            ;;
        -*)
            echo "ERROR: Unknown option '$1'"
            echo "Usage: $0 <input_file> <output_file> [--lookup <file>] [--warnings <file>]"
            exit 1
            ;;
        *)
            if [[ -z "$INPUT" ]]; then
                INPUT="$1"
            elif [[ -z "$OUTPUT" ]]; then
                OUTPUT="$1"
            else
                echo "ERROR: Unexpected argument '$1'"
                exit 1
            fi
            shift
            ;;
    esac
done

if [[ -z "$INPUT" || -z "$OUTPUT" ]]; then
    echo "Usage: $0 <input_file> <output_file> [--lookup <file>] [--warnings <file>]"
    exit 1
fi

if [[ ! -f "$MASTER" ]]; then
    echo "ERROR: Master lookup file not found: $MASTER"
    echo "       Place master_security_auditing_index_micosoft.json in the same directory as this script."
    exit 1
fi

if [[ ! -f "$INPUT" ]]; then
    echo "ERROR: Input file '$INPUT' does not exist."
    exit 1
fi

if [[ -n "$LOOKUP" && ! -f "$LOOKUP" ]]; then
    echo "ERROR: Lookup file '$LOOKUP' does not exist."
    exit 1
fi

# ── Temp files ────────────────────────────────────────────────────────────────
TMP_FLAT=$(mktemp /tmp/pipeline_flat_XXXXXX.ndjson)
TMP_WARN=$(mktemp /tmp/pipeline_warn_XXXXXX.txt)

cleanup() {
    rm -f "$TMP_FLAT" "$TMP_WARN" "${TMP_FLAT}.clean" 2>/dev/null
}
trap cleanup EXIT

# ── Pre-count ─────────────────────────────────────────────────────────────────
TOTAL_LINES=$(wc -l < "$INPUT")
> "$WARNINGS"

# ── Header ────────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║         EVTX JSON Flatten + Normalize Pipeline       ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  Input     : $INPUT"
echo "  Output    : $OUTPUT"
echo "  Master    : $MASTER"
if [[ -n "$LOOKUP" ]]; then
    echo "  Fallback  : $LOOKUP"
else
    echo "  Fallback  : (none)"
fi
echo "  Warnings  : $WARNINGS"
echo "  Lines     : $TOTAL_LINES"
echo ""

# =============================================================================
# STAGE 1: FLATTEN
#
# - Flattens all sections EXCEPT EventData
# - EventData is preserved as-is (nested object)
# - Tags bad records as { "__warn": N }
# =============================================================================

echo "[ STAGE 1 ] Flattening..."
echo ""

jq -cn '
def flatten_obj(prefix; obj):
  reduce (obj | to_entries[]) as $item (
    {};
    ($item.key
      | gsub("#attributes"; "")
      | ltrimstr("_")
      | rtrimstr("_")
    ) as $clean |
    (if prefix == "" then $clean
     else prefix + "_" + $clean
     end) as $full |
    if $clean == "" then
      if ($item.value | type) == "object" then
        . + flatten_obj(prefix; $item.value)
      else . end
    elif ($item.value | type) == "object" then
      . + flatten_obj($full; $item.value)
    elif ($item.value | type) == "array" then
      . + (
        reduce range($item.value | length) as $i (
          {};
          ($full + "_" + ($i | tostring)) as $ak |
          if ($item.value[$i] | type) == "object" then
            . + flatten_obj($ak; $item.value[$i])
          else
            . + { ($ak): $item.value[$i] }
          end
        )
      )
    else
      . + { ($full): $item.value }
    end
  );

def process_event(evt):
  # Separate EventData from all other sections
  (evt | to_entries | map(select(.key != "EventData" and .key != "UserData"))) as $other_sections |
  (evt.EventData // evt.UserData // null) as $event_data |

  # Flatten all non-EventData sections
  (reduce $other_sections[] as $section (
    {};
    if ($section.value | type) == "object" then
      . + flatten_obj(""; $section.value)
    elif ($section.value | type) == "array" then
      . + (
        reduce range($section.value | length) as $i (
          {};
          ($section.key + "_" + ($i | tostring)) as $ak |
          if ($section.value[$i] | type) == "object" then
            . + flatten_obj($ak; $section.value[$i])
          else
            . + { ($ak): $section.value[$i] }
          end
        )
      )
    elif $section.value == null then .
    else . + { ($section.key): $section.value }
    end
  )) as $flat |

  # Return flat fields + EventData as nested object
  $flat + { "EventData": $event_data };

[inputs] |
to_entries[] |
.key as $lineno |
.value as $rec |
if $rec | has("Event") then
  process_event($rec.Event)
else
  { "__warn": ($lineno + 1) }
end
' "$INPUT" > "$TMP_FLAT"

# ── Split warnings ────────────────────────────────────────────────────────────
jq -c 'select(has("__warn") | not)' "$TMP_FLAT" > "${TMP_FLAT}.clean"
jq -r 'select(has("__warn")) | "[WARN] Line \(.__warn) is missing .Event field — skipped."' \
    "$TMP_FLAT" > "$TMP_WARN"

mv "${TMP_FLAT}.clean" "$TMP_FLAT"
cp "$TMP_WARN" "$WARNINGS"

FLAT_RECORDS=$(wc -l < "$TMP_FLAT")
SKIPPED_RECORDS=$(wc -l < "$TMP_WARN")

echo "  Flattened : $FLAT_RECORDS records"
echo "  Skipped   : $SKIPPED_RECORDS records"
echo ""

if [[ $FLAT_RECORDS -eq 0 ]]; then
    echo "ERROR: No records flattened. Check warnings file."
    exit 1
fi

# =============================================================================
# STAGE 2: ENRICH + NORMALIZE
#
# - Builds master map from master_security_auditing_index_micosoft.json (first priority)
# - Builds fallback map from --lookup file (second priority, optional)
# - Merged map: master takes precedence; fallback fills gaps
# - Looks up EventDescription via Provider_Name + EventID
# - Inserts EventDescription right after EventID
# - Renames TimeCreated_SystemTime → TimeGenerated
# - Drops xmlns column
# - EventData stays as nested object
# - No match in either → EventDescription: null
# =============================================================================

echo "[ STAGE 2 ] Enriching with EventDescription..."
echo ""

# Build the jq call dynamically depending on whether --lookup was provided
if [[ -n "$LOOKUP" ]]; then
    jq -cn \
      --slurpfile master "$MASTER" \
      --slurpfile fallback "$LOOKUP" '
    # Build master map: "Provider_EventID" -> Description
    (
      $master[0] |
      map({ ((.Provider + "_" + (.EventID | tostring))): .Description }) |
      add // {}
    ) as $master_map |

    # Build fallback map from generated lookup
    (
      $fallback[0] |
      map({ ((.Provider + "_" + (.EventID | tostring))): .Description }) |
      add // {}
    ) as $fallback_map |

    # Merge: master takes precedence, fallback fills gaps
    ($fallback_map + $master_map) as $lookup_map |

    [inputs] | .[] | . as $rec |

    (($rec.Provider_Name // "") + "_" + ($rec.EventID // "" | tostring)) as $key |
    ($lookup_map[$key] // null) as $description |

    { EventID: $rec.EventID }
    + { EventDescription: $description }
    + (
        $rec
        | del(.EventID)
        | del(.EventData)
        | del(.xmlns)
        | if has("TimeCreated_SystemTime") then
            . + { TimeGenerated: .TimeCreated_SystemTime } | del(.TimeCreated_SystemTime)
          else . end
      )
    + { EventData: $rec.EventData }
    ' "$TMP_FLAT" > "$OUTPUT"
else
    jq -cn \
      --slurpfile master "$MASTER" '
    # Build master map only
    (
      $master[0] |
      map({ ((.Provider + "_" + (.EventID | tostring))): .Description }) |
      add // {}
    ) as $lookup_map |

    [inputs] | .[] | . as $rec |

    (($rec.Provider_Name // "") + "_" + ($rec.EventID // "" | tostring)) as $key |
    ($lookup_map[$key] // null) as $description |

    { EventID: $rec.EventID }
    + { EventDescription: $description }
    + (
        $rec
        | del(.EventID)
        | del(.EventData)
        | del(.xmlns)
        | if has("TimeCreated_SystemTime") then
            . + { TimeGenerated: .TimeCreated_SystemTime } | del(.TimeCreated_SystemTime)
          else . end
      )
    + { EventData: $rec.EventData }
    ' "$TMP_FLAT" > "$OUTPUT"
fi

OUTPUT_RECORDS=$(wc -l < "$OUTPUT")

echo "  Enriched  : $OUTPUT_RECORDS records"
echo ""

# =============================================================================
# SUMMARY
# =============================================================================

echo "╔══════════════════════════════════════════════════════╗"
echo "║                      SUMMARY                        ║"
echo "╚══════════════════════════════════════════════════════╝"
printf "  %-30s %s\n" "Total lines in file:"    "$TOTAL_LINES"
printf "  %-30s %s\n" "Successfully flattened:" "$FLAT_RECORDS"
printf "  %-30s %s\n" "Skipped (no .Event):"    "$SKIPPED_RECORDS"
printf "  %-30s %s\n" "Output records:"         "$OUTPUT_RECORDS"
printf "  %-30s %s\n" "Output:"                 "$OUTPUT"
printf "  %-30s %s\n" "Master lookup:"          "$MASTER"
if [[ -n "$LOOKUP" ]]; then
    printf "  %-30s %s\n" "Fallback lookup:"    "$LOOKUP"
fi
if [[ $SKIPPED_RECORDS -gt 0 ]]; then
    printf "  %-30s %s\n" "Warnings:"           "$WARNINGS"
fi
echo ""
echo "  Done."
echo ""
